// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Th1ROW6cJM0sh20UwofWkag-divbKxQ',
    appId: '1:861917748123:web:103f11eccc105c457b5f3e',
    messagingSenderId: '861917748123',
    projectId: 'arroz-sys',
    authDomain: 'arroz-sys.firebaseapp.com',
    storageBucket: 'arroz-sys.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDel4IU1Czb2h6KS5ttR_IHAJQ6GGn6e0E',
    appId: '1:861917748123:android:451bd52626691d4b7b5f3e',
    messagingSenderId: '861917748123',
    projectId: 'arroz-sys',
    storageBucket: 'arroz-sys.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhRPGkTgb4mB4vZeBw6DXEGvJlI5ibX1A',
    appId: '1:861917748123:ios:a58db8f41663f64f7b5f3e',
    messagingSenderId: '861917748123',
    projectId: 'arroz-sys',
    storageBucket: 'arroz-sys.firebasestorage.app',
    iosBundleId: 'com.example.arrozApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhRPGkTgb4mB4vZeBw6DXEGvJlI5ibX1A',
    appId: '1:861917748123:ios:a58db8f41663f64f7b5f3e',
    messagingSenderId: '861917748123',
    projectId: 'arroz-sys',
    storageBucket: 'arroz-sys.firebasestorage.app',
    iosBundleId: 'com.example.arrozApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4Th1ROW6cJM0sh20UwofWkag-divbKxQ',
    appId: '1:861917748123:web:62b1769444b5eb247b5f3e',
    messagingSenderId: '861917748123',
    projectId: 'arroz-sys',
    authDomain: 'arroz-sys.firebaseapp.com',
    storageBucket: 'arroz-sys.firebasestorage.app',
  );
}
